### PR TITLE
Test for wily installation

### PR DESCRIPTION
**Pull request by leitu**
the script in wily the installation is good, but the performance with qemu is not that good enough. and line 102, I don't understand why it ${${}}, and removed it.

### CODE REVIEW

**Comment by gnawux** [comment]
Thank you @leitu .

One more thing, we will provide native package soon, the curl2bash installation will become deprecated method

**Comment by gnawux** [comment]
by the way, @leitu what do you mean `with qemu`? Is it inside a virtual machine or with kvm acceleration?

**Comment by leitu** [comment]
cool! That will be much easier. Then I will close the comment.
It's with KVM acceleration.

Test on my physical machine.

**Comment by gnawux** [comment]
Could you give some detail about your test? Boot performance or runtime? CPU/memory or IO? Thank you @leitu

**Comment by leitu** [comment]
processor	: 11
MemTotal:       16183860 kB

dd if=/dev/zero of=file.txt count=1024 bs=1024
1024+0 records in
1024+0 records out
1048576 bytes (1.0 MB) copied, 0.00390811 s, 268 MB/s


and it's stuck forever
time hyper run ubuntu:latest
POD id is pod-TCRMRduAOe

**Comment by leitu** [comment]
sorry, my bad, Just figure out what's going on there. When I ran the command as the homepage gif

```
hyper run ubuntu:latest
```

It will none return, untill you ctrl+c, then POD status will be successes. 

But if run as below. :)

```
hyper run -t ubuntu:latest
```

that will get return quickly.  

Hyper is really good to play with.

**Comment by gnawux** [comment]
the new version add option `-t` for tty, as the shell prompts and log info have different requirements. Sorry for that not shown in homepage.

**Pull request closed without merging**
